Worktastic/Models/JobPosting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Worktastic.Models
{
    public class JobPosting
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public string Description { get; set; }
        public int Salary { get; set; }
        public DateTime StartDate { get; set; }
        public string CompanyName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactMail { get; set; }
        public string ContactWebsite { get; set; }
        public byte[] CompanyImage { get; set; }
        public string OwnerUsername { get; set; }
    }
}

Worktastic/Controllers/JobPostingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Worktastic.Data;
using Worktastic.Models;

namespace Worktastic.Controllers
{
    [Authorize]
    public class JobPostingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobPostingController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var allPostings = _context.JobPostings.ToList();
                return View(allPostings);
            }

            var ownerUserJobPostings = _context.JobPostings.Where(x => x.OwnerUsername == User.Identity.Name).ToList();
            return View(ownerUserJobPostings);
        }

        public IActionResult CreateEditJobPosting(int id)
        {
            if (id != 0)
            {
                var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

                if ((jobPostingFromDb.OwnerUsername != User.Identity.Name) && !User.IsInRole("Admin"))
                {
                    return Unauthorized();
                }

                if (jobPostingFromDb != null)
                {
                    return View(jobPostingFromDb);
                }
                else
                {
                    return NotFound();
                }
            }
            return View();
        }

        public IActionResult CreateEditJob(JobPosting jobPosting, IFormFile file)
        {
            jobPosting.OwnerUsername = User.Identity.Name;

            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    file.CopyTo(memoryStream);
                    var imageBytes = memoryStream.ToArray();
                    jobPosting.CompanyImage = imageBytes;
                }
            }

            if (jobPosting.Id == 0)
            {
                // Add new job if not editing
                _context.JobPostings.Add(jobPosting);
            }
            else
            {
                var jobFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == jobPosting.Id);

                if (jobFromDb == null)
                {
                    return NotFound();
                }

                jobFromDb.CompanyImage = jobPosting.CompanyImage;
                jobFromDb.CompanyName = jobPosting.CompanyName;
                jobFromDb.ContactMail = jobPosting.ContactMail;
                jobFromDb.ContactPhone = jobPosting.ContactPhone;
                jobFromDb.ContactWebsite = jobPosting.ContactWebsite;
                jobFromDb.Description = jobPosting.Description;
                jobFromDb.JobLocation = jobPosting.JobLocation;
                jobFromDb.JobTitle = jobPosting.JobTitle;
                jobFromDb.Salary = jobPosting.Salary;
                jobFromDb.StartDate = jobPosting.StartDate;
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteJobPostingById(int id)
        {
            if (id == 0)
            {
                return BadRequest();
            }

            var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

            if (jobPostingFromDb == null)
            {
                return NotFound();
            }

            _context.JobPostings.Remove(jobPostingFromDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Worktastic/Views/JobPosting/CreateEditJobPosting.cshtml
@model Worktastic.Models.JobPosting
@{
    ViewData["Title"] = "Erstellen oder Bearbeiten";
}

<form asp-controller="JobPosting" asp-action="CreateEditJob" enctype="multipart/form-data">
    <div class="card">

        <div class="card-header">
            <h5>Inserat bearbeiten</h5>
        </div>

        <div class="card-body">

            <input hidden asp-for="Id" />

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="JobTitle" type="text" placeholder="Bitte trage eine Job-Bezeichnung ein" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="JobLocation" type="text" placeholder="Bitte trage einen Ort ein" />
                </div>
            </div>
            <div class="row form-group">
                <div class="col">
                    <textarea rows="6" class="form-control" asp-for="Description" placeholder="Bitte trage eine ausführliche Beschreibung ein"></textarea>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-6">
                    <input class="form-control" asp-for="Salary" type="number" placeholder="Wie viel Jahresgehalt zahlt ihr?" />
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <div class="col-form-label">
                        Wann startet der Job?
                    </div>
                    <input class="form-control" asp-for="StartDate" type="date" />
                </div>
            </div>
            <hr />
            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="CompanyName" type="text" placeholder="Wie heißt deine Firma?" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactWebsite" type="url" placeholder="Website" />
                </div>
            </div>
            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="ContactPhone" type="tel" placeholder="Telefonnummer" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactMail" type="email" placeholder="E-Mail Adresse" />
                </div>
            </div>
            <div class="row form-group">
                <div class="col">
                    <label>Bild</label>
                    <input class="form-control-file" name="file" type="file" />
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Speichern</button>
        </div>

    </div>
</form>

Worktastic/Views/JobPosting/Index.cshtml
@model List<JobPosting>
@{    
    ViewData["Title"] = "Deine Inserate";
}

<a class="btn btn-primary" asp-controller="JobPosting" asp-action="CreateEditJobPosting">Neues Inserat anlegen</a>

<table id="jobPostingTable" class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Job Titel</th>
            <th>Ort</th>
            <th>Firmenname</th>
            <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
        @{ 
            foreach(JobPosting jobPosting in Model)
            {
                <tr>
                    <td>@jobPosting.JobTitle</td>
                    <td>@jobPosting.JobLocation</td>
                    <td>@jobPosting.CompanyName</td>
                    <td>
                        <a asp-route-id="@jobPosting.Id" asp-controller="JobPosting" asp-action="CreateEditJobPosting" class="btn btn-warning">Edit</a>
                        <button onclick="onClickedDeleteButton(@jobPosting.Id)" class="btn btn-danger">Löschen</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#jobPostingTable').DataTable();
        });

        function onClickedDeleteButton(id) {
            Swal.fire({
                title: 'Möchtest du das Inserat wirklich löschen?',
                icon: 'error',
                showCloseButton: true,
                focusConfirm: false,
                confirmButtonText: 'Ja, löschen!',
            }).then((result) => {
                if (result.isConfirmed) {
                    // Backend call to delete job posting by id
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("DeleteJobPostingById")",
                        data: { id: id },
                        success: function (msg) {
                            Swal.fire('Wurde gelöscht!', '', 'success').then((result) => {
                                location.reload()
                            })
                        },
                        error: function (msg) {
                            Swal.fire('Ups, etwas ist schief gelaufen!', '', 'error')
                        },
                    });
                }
            })
        }
    </script>
}